src/Commands/Install/FjordInstall.php

* Remove `;` from `composer dumpautoload;`
* [Command "dumpautoload;" is not defined.](https://github.com/aw-studio/fjord/issues/12)

Fix Command "dumpautoload;" is not defined.

---

src/Commands/FjordForm.php

Creating a form via FjordForm leads to an error. Creating the collection folder with a leading uppercase solves the problem.

Fix naming convention

---

docs/docs/getting-started/installation.md

There was a typo on [this page](https://www.fjord-admin.com/docs/getting-started/installation/#setup), just wanted to submit a quick fix.

Fix Laravel typo

---

resources/js/components/Crud/Fields/Relation/FieldRelation.vue

This fix is updating the model via PUT request, before emitting 'reload'.
so, i think everything works for belongsTo.... i think

FielRelation belongsTo

---

src/Fjord/Discover/PackageDiscoverCommand.php

As mentioned in #31 composer's v2 is in alpha, but the fix seems simple, add compatibility with 2.x meanwhile maintains retrocompatibility with 1.x

Add composer v2 compatibility

---

resources/js/components/Fjord/BaseIndex/TableCol/TableCol.vue
src/Page/Table/Column.php
tests/php/Page/ColumnTest.php

This pr makes it possible to give a table column a default value as third parameter. 
```php
$table->col('State')->value('state', ['foo' => 'bar'], 'default value');
```
The following example shows a table with column badges depending on state. If none of the specified options is available, a `secondary` badge with the value of the state attributes is displayed.
```php
$table->col('State')->value('state', [
'success' => '<div class="badge badge-success">Success</div>',
'pending' => '<div class="badge badge-info">Pending</div>',
], '<div class="badge badge-secondary">{state}</div>');
```

Default value for table columns

---

resources/js/components/Crud/Fields/Block/FieldBlock.vue
resources/js/components/Crud/Fields/Block/FieldBlockAddRepeatableButtons.vue
resources/js/components/Crud/Fields/Block/FieldRepeatableHeader.vue
resources/js/components/Crud/Fields/FieldAlertEmpty.vue
resources/js/components/Crud/Fields/FieldAlertNotCreated.vue
resources/js/components/Crud/Fields/Media/FieldMediaImages.vue
resources/js/components/Crud/Fields/Modal/FieldModal.vue
resources/js/components/Crud/Fields/Relation/FieldRelation.vue
resources/js/components/Crud/Fields/Relation/FieldRelationColEdit.vue
resources/js/components/Crud/Fields/Relation/FieldRelationColLink.vue
resources/js/components/Crud/Fields/Relation/FieldRelationColUnlink.vue
resources/js/components/Crud/Fields/Relation/FieldRelationForm.vue
resources/js/components/Crud/Fields/Relation/FieldRelationIndex.vue
resources/js/components/Crud/Preview/CrudPreview.vue
resources/js/components/Fjord/BaseIndex/BaseIndexTableIndexIndicator.vue
resources/js/components/Fjord/BaseIndex/TableForm/BaseIndexTableFilter.vue
resources/js/components/Fjord/BaseIndex/TableForm/BaseIndexTableSearch.vue
resources/js/components/Fjord/BaseIndex/TableForm/BaseIndexTableSort.vue
resources/js/components/Fjord/Navigation.vue
resources/js/components/Permissions/Extensions/PermissionsFjordUsersRoles.vue
resources/js/components/Permissions/Permissions.vue
resources/js/components/Permissions/PermissionsToggle.vue
resources/js/components/Permissions/RoleCreate.vue
resources/js/components/Users/FjordUsers.vue
resources/js/components/Users/UserCreate.vue

This pr replaces the i18n default `$t` method for Laravel like the `__` mixin.

Use __ mixin for js translations

---

resources/js/components/Crud/Fields/DateTime/FieldDateTime.vue
src/Crud/Fields/Datetime.php

This pr adds the `onlyTime` option to the [datetime](https://litstack.io/docs/fields/date-time) field. 
Requested in https://github.com/litstack/litstack/issues/70 
```php
$form->datetime('time')->onlyTime();
```

Added onlyTime options to datetime field

---

resources/js/components/Lit/BaseIndex/BaseIndexTableHead.vue

Fixes #76  - wrong / no font awesome icon on Crud index table when sorting.

fix index table font awesome sort icon

---

src/Crud/Console/FormCommand.php

I stumbled upon the optional {name?} parameter in Ignite\Crud\Console\FormCommand.php, which isn’t mentioned in the docs. But if you try to use it by running „php artisan lit:form NewForm“ you’re still promoted by the configuration wizard to enter the form name once more.
At the moment it’s possible to skip the wizard steps by passing the form name and collection with the corresponding option flags like `—form="NewForm" —collection="FormCollection"`. In my opinion being able to pass just the arguments is a little easier than using option flags. 
This PR makes it possible to skip the wizard if either arguments or option flags are passed to the command.
This way it’s not going to break any existing functionality and still provides an opportunity for a little easier form generation.

Form generator command arguments

---

resources/js/components/Crud/Fields/Select/FieldSelect.vue
src/Crud/Fields/Select.php

**1.** Fixes the `null` string which is shown as selected if the select field has no value.
Before:
**2.** Adds support for a placeholder, as is already exists for other input fields. If no placeholder is specified, the field title is used instead, as provided in the base field.
Without a specified palceholder:
With `->placeholder('...')` method:

Select field placeholder

---

src/Crud/Console/FormCommand.php

Fixes the argument order when creating a new form based on arguments. It now corresponds to the order of the wizard.

fix new form arguments order

---

src/Crud/Repositories/MediaRepository.php

This is a suggestions how the original image dimensions could be saved to the media model when an image is uploaded. 
It is useful for further processing and output. 
Feel free to dismiss this suggestion if it does not meet your criteria.

Store original image dimensions on upload

---

stubs/crud.migration.stub
stubs/crud.migration.translatable.stub

Although they are just an alias for the previous syntax, just writing `$table->id()`  or `$table->foreignId('model_id')` comes really handy and personally I allready prefer it this way. Maybe this could be default for Litstack too?

Update migration stubs to laravel 8 new default column types

---

src/Page/Table/Components/ImageComponent.php

This PR fixes wrong typing of the $square variable in the table image component. 
The expected input value is a string containing the image dimensions, e.g. "50px".

Fixed image column square

---

publish/config/lit.php
src/Application/ApplicationServiceProvider.php

This pr moves providers of litsatck services to the config file so they can be removed, as suggested in https://github.com/litstack/litstack/issues/99.

Move providers to config

---

resources/views/partials/navigation.blade.php
resources/views/partials/topbar/topbar.blade.php

This PR fixes an issue when using an auth guard other than the default `lit` guard. The backend Litstack Vue app was not loading correctly because the navigation could not be displayed.
This issue was also mentioned in https://github.com/litstack/litstack/issues/103#issuecomment-736376399.

Fix navigation auth guard

---

src/Crud/Fields/Route.php

This pr adds the `allowEmpty` method to the route field. This allows the user to select an empty route and by this setting the attribute to `null`.
```php
$form->route('route')->collection('app')->allowEmpty();
```

Add allowEmpty to route field

---

resources/js/components/Crud/Fields/Block/FieldRepeatable.vue
src/Crud/Fields/Block/Block.php

This pr adds the `confirmDelete` to the block field. This adds the option to confirm deletion of a repeatable in a modal. The option is enabled by default.
```php
// Disable confirm delete.
$form->block('content')->confirmDelete(false);
```

Add confirmDelete to Block field

---

publish/database/migrations/______________________make_permissions.php
src/Foundation/Console/InstallCommand.php
src/Foundation/Litstack.php
src/Permissions/Controllers/RoleController.php
src/Support/Migration/MigratePermissions.php
src/User/Console/AdminCommand.php
tests/php/Foundation/LitstackTest.php

This PR adds the changes necessary to make permissions work when using an auth guard other than the default lit guard. 
Also note that `php artisan lit:permissions` must be run when the guard changes.

Fix guard name for permissions

---

src/Crud/Controllers/CrudController.php
src/Crud/CrudShow.php
tests/php/Crud/CrudShowTest.php

This pr adds the ability to load specific model attributes from a crud config.
```php
public function show(CrudShow $page)
{
$page->appends('my_attribute', 'my_other_attribute');
}
```

Add page attributes

---

src/Crud/CrudIndex.php
src/Page/Table/Casts/CarbonColumn.php

1. [#338dae9](https://github.com/litstack/litstack/pull/139/commits/338dae90d575a960206ea8ca100390e9cae7428a) adds a quick fix to prevent the [table `date` method](https://litstack.io/docs/3.x/crud/table#date) to cast `null` values as carbon  instances, as this returns the current date which, may not be the expected result.
2. [#e69a6e8](https://github.com/litstack/litstack/pull/139/commits/e69a6e8a1ef99637aecdccd637d8b23c79c1b1e3) adds the option to use the `info` method to show the info component on a CrudIndex page. Just like it's already possible on the CrudShow page.

Fix table date column casting null values and info component for CrudIndex page

---

src/Support/Macros/CrudMetaMacro.php

Adds the option to chain other methods to the  `meta` macro:
```php
$page->meta()->width(4)->title('Page Meta')
```

Chainable meta macro

---

src/Application/Kernel.php
src/Config/ConfigHandler.php
src/Crud/Config/CrudConfig.php
src/Crud/CrudMiddleware.php
src/Crud/CrudServiceProvider.php
tests/php/Crud/CrudMiddlewareTest.php

This pr fixes crud model binding. This allows to access the session inside the query method of a crud:
```php
public function query($query)
{
$query->where('author_id', lit_user()->id);
}
```

Fix Crud Model Binding

---

src/Application/ApplicationServiceProvider.php

This pr fixes an issue with additional scripts that are specified in the config.

Fix mime type issue

---

src/Support/Macros/CrudMetaMacro.php

Adds the `translatable` method to inputs within the meta macro.

Translatable meta macro inputs

---

resources/js/components/Crud/Fields/Modal/FieldModal.vue

Fixes the duplicate "Change Password" action in User profile:
(and enables the option to open the modal with a custom button component)

Fix duplicate "Change Password" in User profile

---

src/Crud/Repositories/DefaultRepository.php

Prevents the fillOnStore method from parent crud controller to be called when saving / creating a nested relation crud via `$form->relation('xy')->create()`.

Fix calling fillOnStore method for relation crud

---

publish/config/lit.php
resources/views/info.blade.php
resources/views/partials/topbar/navigation.blade.php
src/Info/Controllers/InfoController.php
src/Info/InfoServiceProvider.php
src/Info/RouteServiceProvider.php

This PR enables a simple system info page that can be enabled by registering the `\Ignite\Info\InfoServiceProvider::class`
in the 'providers' key inside the `config/lit.php`.

Show System Info Page

---

resources/js/components/Lit/Info.vue

This PR enables the option to format model attributes within the page info and text component:
```php
$form->info('{title}')->text('{author.name}');
```

Add model attribute formatting for info and text field

---

resources/js/components/Crud/Fields/Relation/FieldRelationColUnlink.vue

Fixes the missing delete or unlink icon and action for crud relation tables.
<details>
<summary>Console errror</summary>
```
[Vue warn]: Error in render: "ReferenceError: field is not defined"
found in
---> <FieldRelationColUnlink> at resources/js/components/Crud/Fields/Relation/FieldRelationColUnlink.vue
```
</details>

Fix unlink / delete relation colum

---

resources/js/components/Crud/Fields/Select/FieldSelect.vue
resources/js/components/Lit/BaseIndex/BaseIndex.vue

This PR fixes some minor css issues:
<details>
<summary>1. Select field breaking</summary>
Before:
After:
</details>
<details>
<summary>2. Responsive table overflow </summary>
Before:
After:
</details>
<br>
This one might be a little opinionated, but i felt the "cut-off" white background to be distracting.
<details>
<summary>3. Selectfield search input background </summary>
Before:
After:
</details>

Minor CSS fixes

---

resources/js/components/Crud/Fields/Field.vue

This is kind of hard to explain, but currently there is a bug within the following scenario:
- Basic litstack setup with only 1 locale (same as fallback locale) in `translatable.php` config.
- lit config locale and fallback_locale are the same
- have a translatable crud, where some input fields use the `translatable()` method (and some not)
- create a new crud model without entering anything to the translatable input fields.
- upload some media for this model
- now the translatable input fields are broken and wont trigger the save button anymore, as the fillValueToModel method tries to access are locale key, that doesn't exist on the model (somehow). Saving to none translatable inputs still work.
- A workaround would be to force an input to one of the translatable fields when creating the …

Fix Editing Translatable Fields When Locale Is Not In Model

---

resources/views/auth/passwords/reset.blade.php
resources/views/landing.blade.php

**Before**:
**After**:
I applied the "overflow-hidden" class to the `landing` template to fix both login and password reset. #172 originally applied this to `index.blade.php`, but that template apparently is not used by the login page at all.

Update reset password screen to match login 

---

resources/js/components/Crud/Fields/dependecy_methods.js
resources/js/components/Lit/BaseComponent.vue
src/Crud/FieldDependency.php
src/Crud/Vue/FieldWrapperGroupComponent.php
src/Vue/Component.php
tests/php/Vue/ComponentTest.php

This pr moves field depencies to the base component class. This means field dependencies can now be used on all components, e.g. actions:
```php
$page->headerRight()->action('Foo', FooAction)->when('type', 'bar');
``` 
Or a card:
```php
$page->card(...)->when('type', 'foo');
```

Vue Component Dependencies

---

src/Crud/Models/Traits/Translatable.php
tests/php/Integration/Crud/TranslatableTraitTest.php

This PR adds support for translated attributes within route model binding, which makes using translated routes even easier.
Assuming `slug` is a translated attribute and within your models `$translatedAttributes` you're able to  use implicit route binding just like for any other, non translated attributes:
```php
Route::trans('/__(routes.blog)/{post:slug}',[BlogController::class,  'show'])->name('blog.show');
```
And using the named route e.g. like this:
```blade
<a href="{{ __route('blog.show', ['post' => $post->slug ])}}">
```
Alternatively, you may of course define a fixed routeKeyName: 
```php
// App\Models\Post
public function getRouteKeyName() {
return 'slug';
}
// routes/web.php
Route::trans('/__(routes.blog)/{post}',[BlogController::class,  'show'])->name('blog.show');
```

Translated route binding

---

resources/js/components/Crud/Fields/Relation/FieldRelation.vue

This should bring back the missing relation link.
I'm actually not sure why the prop is no longer needed, but it breaks the code, so I removed it 🤓.

Fix missing relation link
